# Cloud Build will resolve these at build-time
substitutions:
  _REGION: us-central1
  _SERVICE: watersmartapp
  _REPOSITORY: watersmart-docker
  _IMAGE: watersmart

steps:
# 1. build image
- name: "gcr.io/cloud-builders/docker"
  args: [ "build", "-t",
          "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA",
          "." ]

# 2. push image to Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args: [ "push",
          "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA" ]

# 3. deploy to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "$_SERVICE"
    - "--image"
    - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"
    - "--region"
    - "$_REGION"
    - "--platform"
    - "managed"
    - "--allow-unauthenticated"
    # Uncomment/extend if you need secrets or env vars
    # - "--update-secrets"
    # - "GEE_CREDS=projects/$PROJECT_ID/secrets/gee-creds:latest"

images:
- "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$SHORT_SHA"

options:
  logging: REGIONAL_USER_OWNED_BUCKET